routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/carrier', 'HomeController@carrier')->name('carrier');
Route::get('/policy', 'HomeController@policy')->name('policy');
Route::get('/agreements', 'HomeController@agreements')->name('agreements');
Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/callback/{provider}', 'SocialController@callback');

Route::resources([
    'sender' => 'SenderController',
    'carrier' => 'CarrierController'
]);

Auth::routes();

app/Sender.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sender extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name_from', 'phone_from', 'city_from_id', 'address_from', 'user_id',
        'name_to', 'phone_to', 'city_to_id', 'address_to', 'price', 'notes',
        'date_from', 'date_to'
    ];

    protected $casts = [
        'date_from' => 'datetime',
        'date_to' => 'datetime',
    ];
    //

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function city_from() {
        return $this->belongsTo('App\City','city_from_id');
    }

    public function city_to() {
        return $this->belongsTo('App\City','city_to_id');
    }

    public function hasAttribute($attr) {
        return array_key_exists($attr, $this->attributes);
    }

}

app/Http/Controllers/SenderController.php
<?php

namespace App\Http\Controllers;

use App\Sender;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;

class SenderController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth',['except' => ['index','create','store','show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = request()->all();

        $senders = \App\Sender::whereNotNull('id');
        foreach($data as $key=>$value) {
            if(isset($value) && Schema::hasColumn((new \App\Sender())->getTable(), $key)) {
                $senders = $senders->where($key,$value);
            }
        }
        
        return view('sender.index',['senders' => $senders->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sender.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->all());
        $data = $request->all();
        
        if(isset($data['dates'])) {
            $dates = explode(' - ',$data['dates']);
            unset($data['dates']);
            $data['date_from'] = preg_replace('/^(\d{2}).(\d{2}).(\d{4})$/','$3-$2-$1',$dates[0]);
            $data['date_to'] = preg_replace('/^(\d{2}).(\d{2}).(\d{4})$/','$3-$2-$1',$dates[1]);
        }

        if(\Auth::check()) {
            $data['user_id'] = \Auth::user()->id;
        }

        $sender = \App\Sender::create($data);

        if(isset($sender))
            return redirect()->route('sender.index');


        return redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sender  $sender
     * @return \Illuminate\Http\Response
     */
    public function show(Sender $sender)
    {
        if($sender->user_id > 0) $this->middleware('auth');
        return view('sender.show',['sender' => $sender]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sender  $sender
     * @return \Illuminate\Http\Response
     */
    public function edit(Sender $sender)
    {
        if($sender->user_id == \Auth::user()->id) return view('sender.edit',['sender' => $sender]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sender  $sender
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sender $sender)
    {

        $data = $request->all();
        if(isset($data['dates'])) {
            $dates = explode(' - ',$data['dates']);
            unset($data['dates']);
            $data['date_from'] = preg_replace('/^(\d{2}).(\d{2}).(\d{4})$/','$3-$2-$1',$dates[0]);
            $data['date_to'] = preg_replace('/^(\d{2}).(\d{2}).(\d{4})$/','$3-$2-$1',$dates[1]);
        }

        $sender->update($data);
        $sender->save();

        return redirect()->route('sender.show',$sender);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sender  $sender
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sender $sender)
    {
        $sender->delete();
        return redirect()->route('sender.index')->withInput();
    }
}

resources/views/sender/create.blade.php
@extends('app')

@section('content')


	<form class="contact100-form validate-form" action="{!! route('sender.store') !!}" method="POST">
		@csrf
		<span class="contact100-form-title">
			Нужно передать
		</span>
		<span class="contact100-form-desc">
			Создать объявление
		</span>
		
		<div class="wrap-input100 validate-input bg0 rs1-alert-validate" data-validate="Заполните описание">
			<i class="fa fa-envelope-o"></i>
			<span class="label-input100">Описание передачи</span>
			<textarea class="input100" name="notes" placeholder="например, коробка с вещами весом 4кг, габариты 50см на 50см на 40см"></textarea>
		</div>

		{{--  --}}

		<div class="wrap-input100 validate-input bg1" data-validate="Обязательное поле">
			<i class="fa fa-calendar"></i>
			<span class="label-input100">Даты отправления - доставки</span>
			<input class="input100" type="text" name="dates">
		</div>

		<div class="wrap-input100 validate-input bg1 rs1-wrap-input100" data-validate="Обязательное поле">
			<i class="fa fa-user-circle"></i>
			<span class="label-input100">Имя отправителя</span>
			@if(\Auth::check())
			<input type="hidden" name="name_from" value="{!! \Auth::check() ?  \Auth::user()->name : '' !!}" />
			@endif
			<input class="input100" type="text" @if(\Auth::check()) disabled @endif  name="name_from" value="{!! \Auth::check() ?  \Auth::user()->name : '' !!}" placeholder="например, Кажыгумар" required>
		</div>

		<div class="wrap-input100 bg1 rs1-wrap-input100">
			<i class="fa fa-phone"></i>
			<span class="label-input100">Контактный телефон отправителя</span>
			<input class="input100" type="text" name="phone_from" value="" placeholder="+7 (777) 426 05 76">
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-arrow-up"></i>
			<span class="label-input100">Город отправления</span> 
			<div>
				<select class="js-select2" name="city_from_id" placeholder="{!! __('Выберите город отправления') !!}">
					@foreach (\App\City::all() as $city)
					<option value="{!! $city->id !!}">{!! $city->name . ', ' . $city->name_kz . ', ' . $city->region !!}</option>
					@endforeach
				</select>
				<div class="dropDownSelect2"></div>
			</div>
		</div>

		<div class="wrap-input100 validate-input bg1 rs1-wrap-input100">
			<i class="fa fa-address-card"></i>
			<span class="label-input100">Введите адрес отправления</span>
			<input class="input100" type="text" name="address_from"
				placeholder="например, мкр.Самал-2, 87, кв. 55">
		</div>

		<div class="wrap-input100 bg1 rs1-wrap-input100">
			<i class="fa fa-user-circle"></i>
			<span class="label-input100">Имя получателя</span>
			<input class="input100" type="text" name="name_to"
				placeholder="например, Габдуллин Аман">
		</div>

		<div class="wrap-input100 bg1 rs1-wrap-input100">
			<i class="fa fa-phone"></i>
			<span class="label-input100">Контактный телефон получателя</span>
			<input class="input100" type="text" name="phone_to"
				placeholder="+7 (777) 426 05 76">
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-arrow-down"></i>
			<span class="label-input100">Город доставки</span>
			<div>
				<select class="js-select2" name="city_to_id" placeholder="{!! __('Выберите город доставки') !!}">
					@foreach (\App\City::all() as $city)
					<option value="{!! $city->id !!}">{!! $city->name . ', ' . $city->name_kz . ', ' . $city->region !!}</option>
					@endforeach
				</select>
				<div class="dropDownSelect2"></div>
			</div>
		</div>

		<div class="wrap-input100 bg1 rs1-wrap-input100">
			<i class="fa fa-address-card"></i>
			<span class="label-input100">{{__('Введите адрес доставки')}}</span>
			<input class="input100" type="text" name="address_to" placeholder="например, ул.Бозтаева, 39, кв. 67">
		</div>

		<div class="rs1-wrap-input100">
			<a class="contact100-form-btn" href="{!! route('sender.index') !!}">
				<span>
					{!! __('Go Back') !!}
					<i class="fa fa-arrow-left m-l-7" aria-hidden="true"></i>
				</span>
			</a>
		</div>

		<div class="rs1-wrap-input100">
			<button class="contact100-form-btn" type="submit">
				<span>
					{!! __('Подать объявление') !!}
					<i class="fa fa-edit m-l-7" aria-hidden="true"></i>
				</span>
			</button>
		</div>
	</form>



@endsection


@section('js')
<!--===============================================================================================-->
<script src="/vendor/daterangepicker/moment.min.js"></script>
<script src="/vendor/daterangepicker/daterangepicker.js"></script>
<script>
	$('input[name="dates"]').daterangepicker({
		timePicker: false,
		locale: {
			format: 'DD/MM/YYYY'
		}
	});
</script>
<!--===============================================================================================-->
	<script src="/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
@endsection

resources/views/sender/edit.blade.php
@extends('app')

@section('content')

	<form class="contact100-form validate-form" action="{!! route('sender.update',$sender) !!}" method="POST">
		@csrf
		@method('PUT')

		<span class="contact100-form-title">
			{{ __('Нужно передать')}}
		</span>
		<span class="contact100-form-desc">
			{{ __('Исправить объявление')}}
		</span>
		
		<div class="wrap-input100 validate-input bg0 rs1-alert-validate" data-validate="Заполните описание">
			<i class="fa fa-envelope-o"></i>
			<span class="label-input100">{{ __('Описание передачи')}}</span>
			<textarea class="input100" name="notes" placeholder="например, коробка с вещами весом 4кг, габариты 50см на 50см на 40см">{!! $sender->notes !!}</textarea>
		</div>

		<div class="wrap-input100 validate-input bg1" data-validate="Обязательное поле">
			<i class="fa fa-calendar"></i>
			<span class="label-input100">Даты отправления - доставки</span>
			<input class="input100" type="text" name="dates" />
		</div>

		<div class="wrap-input100 validate-input bg1 rs1-wrap-input100" data-validate="Обязательное поле">
			<i class="fa fa-user-circle"></i>
			<span class="label-input100">{{ __('Имя отправителя')}}</span>
			@if(\Auth::check())
			<input type="hidden" name="name_from" value="{!! \Auth::check() ?  \Auth::user()->name : '' !!}" />
			@endif
			<input class="input100" type="text" @if(\Auth::check()) disabled @endif name="name_from" value="{!! $sender->name_from !!}" placeholder="например, Кажыгумар" required>
		</div>

		<div class="wrap-input100 validate-input bg1 rs1-wrap-input100" data-validate="Обязательное поле">
			<i class="fa fa-phone"></i>
			<span class="label-input100">{{ __('Контактный телефон отправителя')}}</span>
			<input class="input100" type="text" name="phone_from" value="{!! $sender->phone_from !!}" placeholder="+7 (777) 426 05 76" required>
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-arrow-up"></i>
			<span class="label-input100">{{ __('Город отправления')}}</span> 
			<div>
				<select class="js-select2" name="city_from_id" placeholder="{!! __('Выберите город отправления') !!}">
					@foreach (\App\City::all() as $city)
					<option @if($city->id == $sender->city_from_id) selected @endif
						value="{!! $city->id !!}">{!! $city->name . ', ' . $city->name_kz . ', ' . $city->region !!}</option>
					@endforeach
				</select>
				<div class="dropDownSelect2"></div>
			</div>
		</div>

		<div class="wrap-input100 validate-input bg1 rs1-wrap-input100" data-validate="Обязательное поле">
			<i class="fa fa-address-card"></i>
			<span class="label-input100">{{ __('Введите адрес отправления')}}</span>
			<input class="input100" type="text" name="address_from" value="{!! $sender->address_from !!}"
				placeholder="например, мкр.Самал-2, 87, кв. 55" required>
		</div>

		<div class="wrap-input100 bg1 rs1-wrap-input100" data-validate="Обязательное поле">
			<i class="fa fa-user-circle"></i>
			<span class="label-input100">Имя получателя</span>
			<input class="input100" type="text" name="name_to" value="{!! $sender->name_to !!}"
				placeholder="например, Габдуллин Аман">
		</div>

		<div class="wrap-input100 bg1 rs1-wrap-input100" data-validate="Обязательное поле">
			<i class="fa fa-phone"></i>
			<span class="label-input100">Контактный телефон получателя</span>
			<input class="input100" type="text" name="phone_to" value="{!! $sender->phone_to !!}"
				placeholder="+7 (777) 426 05 76">
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-arrow-down"></i>
			<span class="label-input100">Город доставки</span>
			<div>
				<select class="js-select2" name="city_to_id" placeholder="{!! __('Выберите город доставки') !!}">
					@foreach (\App\City::all() as $city)
					<option @if($city->id == $sender->city_to_id) selected @endif
						value="{!! $city->id !!}">{!! $city->name . ', ' . $city->name_kz . ', ' . $city->region !!}</option>
					@endforeach
				</select>
				<div class="dropDownSelect2"></div>
			</div>
		</div>

		<div class="wrap-input100 bg1 rs1-wrap-input100" data-validate="Обязательное поле">
			<i class="fa fa-address-card"></i>
			<span class="label-input100">Введите адрес доставки</span>
			<input class="input100" type="text" name="address_to"  value="{!! $sender->address_to !!}" placeholder="например, ул.Бозтаева, 39, кв. 67">
		</div>

		<div class="rs1-wrap-input100">
			<a class="contact100-form-btn" href="{!! route('sender.show',$sender->id) !!}">
				<span>
					{!! __('Go Back') !!}
					<i class="fa fa-arrow-left m-l-7" aria-hidden="true"></i>
				</span>
			</a>
		</div>

		<div class="rs1-wrap-input100">
			<button class="contact100-form-btn" type="submit">
				<span>
					{{ __('Edit') }}
					<i class="fa fa-edit m-l-7" aria-hidden="true"></i>
				</span>
			</button>
		</div>
	</form>


@endsection


@section('js')
<!--===============================================================================================-->
<script src="/vendor/daterangepicker/moment.min.js"></script>
<script src="/vendor/daterangepicker/daterangepicker.js"></script>
<script>
	$('input[name="dates"]').daterangepicker({
		timePicker: false,
		startDate: moment('{!! $sender->date_from !!}','YYYY-MM-DD'),
		endDate: moment('{!! $sender->date_to !!}','YYYY-MM-DD'),
		locale: {
			format: 'DD/MM/YYYY'
		}
	});
</script>
<!--===============================================================================================-->
	<script src="/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
@endsection

resources/views/sender/index.blade.php
@extends('app')

@section('content')

	<form class="contact100-form" action="{!! route('sender.index') !!}" method="GET">
		{{-- @csrf --}}
		<span class="contact100-form-title">
			Нужно отправить
		</span>
		<span class="contact100-form-desc">
			Список объявлений на отправление
		</span>

		{{-- <div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-arrow-up"></i>
			<span class="label-input100">Способ доставки</span>
			<div>
				<select class="js-select2" id="transport" name="transport_id">
					<option value="">{!! __('Выберите значение') !!}</option>
					@foreach (\App\Transport::all() as $transport)
					<option value="{!! $transport->id !!}"
						@if(request('transport_id') == $transport->id) selected @endif
					>{!! $transport->name !!}</option>
					@endforeach
				</select>
				<div class="dropDownSelect2"></div>
			</div>
		</div> --}}

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-arrow-up"></i>
			<span class="label-input100">Город отправления</span> 
			<div>
				<select class="js-select2" name="city_from_id" placeholder="{!! __('Выберите город отправления') !!}">
					<option value="">{!! __('Выберите значение') !!}</option>
					@foreach (\App\City::all() as $city)
					<option
						@if($city->id == request('city_from_id')) selected @endif
						value="{!! $city->id !!}">{!! $city->name . ', ' . $city->name_kz . ', ' . $city->region !!}</option>
					@endforeach
				</select>
				<div class="dropDownSelect2"></div>
			</div>
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-arrow-down"></i>
			<span class="label-input100">Город доставки</span>
			<div>
				<select class="js-select2" name="city_to_id" placeholder="{!! __('Выберите город доставки') !!}">
					<option value="">{!! __('Выберите значение') !!}</option>
					@foreach (\App\City::all() as $city)
					<option 
						@if($city->id == request('city_to_id')) selected @endif
						value="{!! $city->id !!}">{!! $city->name . ', ' . $city->name_kz . ', ' . $city->region !!}</option>
					@endforeach
				</select>
				<div class="dropDownSelect2"></div>
			</div>
		</div>

		<div class="rs1-wrap-input100">
			<button class="contact100-form-btn">
				<span>
					{!! __('Search') !!}
					<i class="fa fa-search m-l-7" aria-hidden="true"></i>
				</span>
			</button>
		</div>
		

	</form>

	<div class="contact100-form mt-2">
		@foreach ($senders as $sender)
		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			{{-- <img class="card-img-top" src="/" alt="Card image cap"> --}}
			<div class="card-body">
				<h5 class="card-title">{!! $sender->name !!}</h5>
				<p class="card-text"><strong><pre>{!! $sender->notes !!}</pre></strong></p>
				<p class="card-text"><strong>{!! __('Город отправления/доставки') !!}</strong>: {!! $sender->city_from->name !!} / {!! $sender->city_to->name !!}</p>
				<p class="card-text"><strong>{!! __('Время отправления/доставки') !!}</strong>: {!! date('d/m/Yг',strtotime($sender->date_from)) !!} / {!! date('d/m/Yг',strtotime($sender->date_to)) !!}</p>
				@if(!$sender->auth_id || \Auth::check())
				<a href="{!! route('sender.show',$sender->id) !!}" class="btn btn-link">{{__('Show')}}</a>
				@else
				<a href="{!! route('login') !!}" class="btn btn-link">{!! __('Чтобы увидеть детали, войдите в систему') !!}</a>
				@endif
			</div>
		</div>	
		@endforeach

	</div>

	<div class="contact100-form mt-2">
		<div class="rs1-wrap-input100 mt-2">
			<a href="{!! route('sender.create') !!}" class="contact100-form-btn">
				<span>
					{!! __('Новое отправление')!!}
					<i class="fa fa-plus m-l-7" aria-hidden="true"></i>
				</span>
			</a>
		</div>
	</div>



@endsection


@section('js')
<!--===============================================================================================-->
	<script src="/vendor/daterangepicker/moment.min.js"></script>
	<script src="/vendor/daterangepicker/daterangepicker.js"></script>
	<script>
		$('input[name="dates"]').daterangepicker({
			timePicker: false,
			@if(request()->has('dates'))
			startDate: moment('{!! explode(' - ',request('dates'))[0] !!}','DD/MM/YYYY'),
			endDate: moment('{!! explode(' - ',request('dates'))[1] !!}','DD/MM/YYYY'),
			@endif
			locale: {
				format: 'DD/MM/YYYY'
			}
		});
	</script>
<!--===============================================================================================-->
	<script src="/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/vendor/noui/nouislider.min.js"></script>
	<script>
	    var filterBar = document.getElementById('filter-bar');

	    noUiSlider.create(filterBar, {
	        start: [ 1500, 3900 ],
	        connect: true,
	        range: {
	            'min': 1500,
	            'max': 7500
	        }
	    });

	    var skipValues = [
	    document.getElementById('value-lower'),
	    document.getElementById('value-upper')
	    ];

	    filterBar.noUiSlider.on('update', function( values, handle ) {
	        skipValues[handle].innerHTML = Math.round(values[handle]);
	        $('.contact100-form-range-value input[name="from-value"]').val($('#value-lower').html());
	        $('.contact100-form-range-value input[name="to-value"]').val($('#value-upper').html());
	    });
	</script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
@endsection

resources/views/sender/show.blade.php
@extends('app')

@section('content')


	<form class="contact100-form" action="{!! route('sender.index') !!}" method="GET">
		{{-- @csrf --}}
		<span class="contact100-form-title">
			{!! __('Нужно отправить') !!}
		</span>
		<span class="contact100-form-desc">
			{!! $sender->notes !!}
		</span>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-clock-o"></i>
			<span class="label-input100">{{ __('Date From') }}</span> 
			<p class="label-input100">{!! date('d/m/Yг',strtotime($sender->date_from)) !!}</p>
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-clock-o"></i>
			<span class="label-input100">{{ __('Date To') }}</span> 
			<p class="label-input100">{!! date('d/m/Yг',strtotime($sender->date_to)) !!}</p> 
			
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-user"></i>
			<span class="label-input100">{{ __('Sender name') }}</span> 
			<p class="label-input100">{!! $sender->name_from!!}</p> 
			
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-phone"></i>
			<span class="label-input100">{{ __('Sender phone') }}</span> 
			<p class="label-input100">{!! $sender->phone_from!!}</p> 
			
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-building-o"></i>
			<span class="label-input100">{{ __('Город отправления') }}</span> 
			<p class="label-input100">{!! $sender->city_from->full_name!!}</p> 
			
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-home"></i>
			<span class="label-input100">{{ __('Адрес отправления') }}</span> 
			<p class="label-input100">{!! $sender->address_from!!}</p> 
			
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-user"></i>
			<span class="label-input100">{{ __('Receiver name') }}</span> 
			<p class="label-input100">{!! $sender->name_to!!}</p> 
			
		</div>

		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-phone"></i>
			<span class="label-input100">{{ __('Receiver phone') }}</span> 
			<p class="label-input100">{!! $sender->phone_to!!}</p> 
			
		</div>
		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-building-o"></i>
			<span class="label-input100">{{ __('Город доставки') }}</span>
			<p class="label-input100">{!! $sender->city_to->full_name!!}</p> 
		</div>
		
		<div class="wrap-input100 input100-select bg1 rs1-wrap-input100">
			<i class="fa fa-home"></i>
			<span class="label-input100">{{ __('Адрес доставки') }}</span> 
			<p class="label-input100">{!! $sender->address_to!!}</p> 
			
		</div>

	</form>

	@if($sender->user_id == \Auth::user()->id)

	<form class="contact100-form" action="{!! route('sender.destroy',$sender) !!}" method="POST">
		@csrf
		@method('DELETE')

		<div class="rs1-wrap-input100">
			<a class="contact100-form-btn" href="{!! route('sender.edit',$sender->id) !!}">
				<span>
					{!! __('Edit') !!}
					<i class="fa fa-edit m-l-7" aria-hidden="true"></i>
				</span>
			</a>
		</div>
		
		<div class="rs1-wrap-input100">
			<button class="contact100-form-btn" type="submit" onclick="return confirm('Удалить?')">
				<span>
					{!! __('Soft Delete') !!}
					<i class="fa fa-trash m-l-7" aria-hidden="true"></i>
				</span>
			</button>
		</div>
	</form>
	@endif



@endsection


@section('js')
<!--===============================================================================================-->
	<script src="/vendor/daterangepicker/moment.min.js"></script>
	<script src="/vendor/daterangepicker/daterangepicker.js"></script>
	<script>
		$('input[name="dates"]').daterangepicker();
	</script>
<!--===============================================================================================-->
	<script src="/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/vendor/noui/nouislider.min.js"></script>
	<script>
	    var filterBar = document.getElementById('filter-bar');

	    noUiSlider.create(filterBar, {
	        start: [ 1500, 3900 ],
	        connect: true,
	        range: {
	            'min': 1500,
	            'max': 7500
	        }
	    });

	    var skipValues = [
	    document.getElementById('value-lower'),
	    document.getElementById('value-upper')
	    ];

	    filterBar.noUiSlider.on('update', function( values, handle ) {
	        skipValues[handle].innerHTML = Math.round(values[handle]);
	        $('.contact100-form-range-value input[name="from-value"]').val($('#value-lower').html());
	        $('.contact100-form-range-value input[name="to-value"]').val($('#value-upper').html());
	    });
	</script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
@endsection